# Generated by Django 6.0.3 on 2026-03-27 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Cinema', 'Cinema'), ('Theatre/Auditorium', 'Theatre / Auditorium'), ('Meeting', 'Meeting'), ('Boardroom', 'Boardroom'), ('Lounge', 'Lounge'), ('Refreshment', 'Refreshment')], max_length=30)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('best_for', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('out_of_order', 'Out of Order')], default='vacant', max_length=20)),
                ('cleaning_start', models.TimeField(default='06:00')),
                ('cleaning_end', models.TimeField(default='08:00')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField(blank=True, default='')),
                ('organizer_name', models.CharField(max_length=200)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('organizer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('daily_schedules', models.JSONField(blank=True, default=list)),
                ('participant_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved (Pending)'), ('approved', 'Approved (Awaiting Payment)'), ('confirmed', 'Confirmed (Paid)'), ('override', 'VIP Override'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='reserved', max_length=20)),
                ('letter_attachment', models.FileField(blank=True, null=True, upload_to='booking_letters/')),
                ('ict_acknowledged', models.BooleanField(default=False)),
                ('catering_acknowledged', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('venue_daily_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('service_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
                ('support_services', models.ManyToManyField(blank=True, related_name='bookings', to='conference.supportservice')),
                ('technical_services', models.ManyToManyField(blank=True, related_name='bookings', to='conference.technicalservice')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='conference.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('organizer', 'Event Organizer'), ('event_management', 'Event Management'), ('ict_admin', 'ICT / Sys Admin'), ('catering_support', 'Catering & Support'), ('admin_finance', 'Admin & Finance'), ('leadership', 'Ministry Leadership'), ('system_admin', 'System Administrator')], default='organizer', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='conference.booking')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.systemuser')),
            ],
            options={
                'unique_together': {('booking', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_updates', to='conference.venue')),
            ],
            options={
                'unique_together': {('venue', 'date')},
            },
        ),
    ]
