# Generated by Django 6.0.3 on 2026-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='included_services',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
