# Generated by Django 6.0.3 on 2026-03-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_venue_included_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('approved', 'Approval (Pending Payment)'), ('confirmed', 'Payment Confirmed'), ('rejected', 'Booking Rejected'), ('reminder_24h', '24h Event Reminder'), ('reminder_48h_pay', '48h Payment Expiration'), ('last_day', 'Meeting Conclusion')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='expiration_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
