# Generated by Django 6.0.3 on 2026-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_emailtemplate_booking_expiration_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='catering_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='catering_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='ict_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='ict_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
