# Generated by Django 6.0.3 on 2026-03-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_booking_catering_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unavailable_technical_services',
            field=models.ManyToManyField(blank=True, related_name='unavailable_for_bookings', to='conference.technicalservice'),
        ),
    ]
