# Generated by Django 6.0.3 on 2026-03-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_booking_unavailable_technical_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unavailable_support_services',
            field=models.ManyToManyField(blank=True, related_name='unavailable_support_for_bookings', to='conference.supportservice'),
        ),
    ]
