# Generated by Django 6.0.3 on 2026-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_booking_unavailable_support_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / Awaiting Action'), ('partial_paid', '1st Round Paid'), ('paid', 'Fully Paid'), ('approved', 'VIP Approved'), ('rejected', 'Rejected (e.g. VIP Override)'), ('cancelled', 'Cancelled by User/Admin'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='trigger',
            field=models.CharField(choices=[('pending', 'Booking Received (Pending)'), ('partial_paid', '1st Round Payment Confirmed'), ('paid', 'Full Payment Confirmed'), ('approved', 'VIP Override Approved'), ('rejected', 'Booking Rejected / Overridden'), ('cancelled', 'Booking Cancelled'), ('completed', 'Event Completed'), ('reminder_24h', '24h Event Reminder'), ('reminder_48h_pay', '48h Payment Expiration'), ('last_day', 'Meeting Conclusion')], max_length=50, unique=True),
        ),
    ]
