import { Venue, TechnicalService, SupportService, Booking } from './types';

export const venues: Venue[] = [
  { id: 'v1', name: 'Abol Hall', type: 'Cinema', capacity: 850, bestFor: 'Large conferences & national events', price: null },
  { id: 'v2', name: 'Adey Hall', type: 'Theatre/Auditorium', capacity: 90, bestFor: 'Workshops & panel discussions', price: null },
  { id: 'v3', name: 'Adey Hall A', type: 'Theatre/Auditorium', capacity: 50, bestFor: 'Mid-size trainings & symposia', price: null },
  { id: 'v4', name: 'Adey Hall B', type: 'Theatre/Auditorium', capacity: 40, bestFor: 'Breakout sessions', price: null },
  { id: 'v5', name: 'Lamebora Hall', type: 'Meeting', capacity: 40, bestFor: 'Standard meetings', price: null },
  { id: 'v6', name: 'Lamebora Hall A', type: 'Meeting', capacity: 26, bestFor: 'Small meetings', price: null },
  { id: 'v7', name: 'Lamebora Hall B', type: 'Meeting', capacity: 14, bestFor: 'Very small meetings', price: null },
  { id: 'v8', name: 'VIP Board Room', type: 'Boardroom', capacity: 12, bestFor: 'High-level / ministerial meetings', price: null },
  { id: 'v9', name: 'VIP Lounge Area', type: 'Lounge', capacity: null, bestFor: 'Networking & refreshments', price: null },
  { id: 'v10', name: 'VIP Refreshment Area', type: 'Refreshment', capacity: null, bestFor: 'Catering support', price: null },
];

export const technicalServices: TechnicalService[] = [
  { id: 'ts1', name: 'Internet Access' },
  { id: 'ts2', name: 'HDMI Connection' },
  { id: 'ts3', name: 'Wireless Sharing' },
  { id: 'ts4', name: 'LED Screen / Display' },
  { id: 'ts5', name: 'Microphone' },
  { id: 'ts6', name: 'Sound System' },
  { id: 'ts7', name: 'Video Conferencing' },
  { id: 'ts8', name: 'Photography' },
  { id: 'ts9', name: 'Meeting Recording' },
  { id: 'ts10', name: 'Livestreaming' },
  { id: 'ts11', name: 'Interpretation System' },
  { id: 'ts12', name: 'Presentation Laptop' },
];

export const supportServices: SupportService[] = [
  { id: 'ss1', name: 'Stationery' },
  { id: 'ss2', name: 'Coffee Break' },
  { id: 'ss3', name: 'Lunch Catering' },
  { id: 'ss4', name: 'Water Service' },
  { id: 'ss5', name: 'Registration Desk' },
  { id: 'ss6', name: 'Event Signage' },
  { id: 'ss7', name: 'Reception Support' },
  { id: 'ss8', name: 'Security Support' },
  { id: 'ss9', name: 'Cleaning Service' },
];

export const initialBookings: Booking[] = [
  {
    id: 'b1',
    venueId: 'v1',
    eventTitle: 'National Agriculture Policy Review',
    eventDescription: 'Annual review of national agriculture policies with stakeholders from all regions.',
    organizerName: 'Abera Tadesse',
    organizerEmail: 'abera.t@moa.gov.et',
    organizerPhone: '+251911234567',
    startDate: '2026-03-23',
    endDate: '2026-03-23',
    startTime: '09:00',
    endTime: '17:00',
    participantCount: 420,
    status: 'confirmed',
    technicalServices: ['ts1', 'ts4', 'ts5', 'ts6', 'ts7', 'ts10'],
    supportServices: ['ss2', 'ss3', 'ss4', 'ss5', 'ss6', 'ss9'],
    createdAt: '2026-03-10T08:00:00Z',
  },
  {
    id: 'b2',
    venueId: 'v2',
    eventTitle: 'Soil Conservation Workshop',
    eventDescription: 'Training on modern soil conservation techniques for regional officers.',
    organizerName: 'Tigist Hailu',
    organizerEmail: 'tigist.h@moa.gov.et',
    organizerPhone: '+251922345678',
    startDate: '2026-03-24',
    endDate: '2026-03-24',
    startTime: '08:30',
    endTime: '12:30',
    participantCount: 65,
    status: 'reserved',
    technicalServices: ['ts1', 'ts2', 'ts5', 'ts12'],
    supportServices: ['ss1', 'ss2', 'ss4'],
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'b3',
    venueId: 'v5',
    eventTitle: 'Quarterly Budget Planning',
    eventDescription: 'Internal budget review and planning session for Q2.',
    organizerName: 'Dawit Mengistu',
    organizerEmail: 'dawit.m@moa.gov.et',
    organizerPhone: '+251933456789',
    startDate: '2026-03-25',
    endDate: '2026-03-25',
    startTime: '14:00',
    endTime: '16:30',
    participantCount: 18,
    status: 'reserved',
    technicalServices: ['ts1', 'ts2'],
    supportServices: ['ss4'],
    createdAt: '2026-03-18T09:00:00Z',
  },
  {
    id: 'b4',
    venueId: 'v8',
    eventTitle: 'Minister\'s Briefing on Food Security',
    eventDescription: 'High-level briefing on the current food security situation.',
    organizerName: 'Sara Bekele',
    organizerEmail: 'sara.b@moa.gov.et',
    organizerPhone: '+251944567890',
    startDate: '2026-03-26',
    endDate: '2026-03-26',
    startTime: '10:00',
    endTime: '11:30',
    participantCount: 10,
    status: 'confirmed',
    technicalServices: ['ts1', 'ts4', 'ts5', 'ts7'],
    supportServices: ['ss2', 'ss4'],
    createdAt: '2026-03-12T14:00:00Z',
  },
];
